In [1]:
import numpy as np

In [5]:
array1 = np.array([[1.0,2,3],[4.0,5,6]])
print(array1.dtype)
print(array1.size)
print(array1.shape)

float64
6
(2, 3)


In [7]:
np.random.randint(10,size=(8,20))

array([[3, 1, 3, 9, 8, 4, 1, 0, 5, 6, 2, 4, 3, 0, 8, 2, 0, 7, 0, 6],
       [9, 2, 0, 5, 9, 4, 6, 4, 2, 9, 6, 1, 6, 5, 7, 9, 1, 4, 9, 6],
       [9, 6, 4, 3, 4, 1, 1, 7, 3, 4, 1, 6, 3, 4, 6, 6, 7, 9, 7, 1],
       [2, 6, 4, 5, 3, 5, 5, 0, 0, 2, 3, 7, 1, 1, 0, 1, 2, 6, 5, 4],
       [6, 9, 2, 6, 1, 3, 7, 0, 7, 5, 2, 6, 7, 1, 8, 7, 4, 6, 8, 0],
       [3, 9, 0, 6, 9, 2, 3, 3, 9, 3, 5, 7, 0, 3, 7, 8, 5, 2, 5, 9],
       [5, 0, 8, 7, 7, 8, 5, 0, 5, 2, 2, 6, 7, 2, 5, 1, 8, 7, 0, 1],
       [3, 1, 6, 8, 7, 3, 4, 2, 0, 7, 9, 0, 0, 9, 2, 1, 1, 5, 9, 5]])

In [8]:
np.random.randint(10,size=20).reshape(4,5)

array([[2, 6, 0, 6, 9],
       [7, 8, 5, 5, 5],
       [4, 4, 3, 9, 2],
       [1, 1, 3, 5, 6]])

In [11]:
# 创建矩阵
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [12]:
np.unique(array1)

array([1., 2., 3., 4., 5., 6.])

In [14]:
sum(array1)

array([5., 7., 9.])

In [16]:
# 使用pickle序列化numpy array
import pickle

x = np.arange(10)

In [18]:
f = open('x.pkl','wb')
pickle.dump(x,f)
!ls

LICENSE                             tf_basic_api.ipynb
README.md                           tf_keras_regression-hp-search.ipynb
learn_numpy.ipynb                   x.pkl


In [19]:
f = open('x.pkl','rb')
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])